/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-336
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3.js';


// Services


// Functions
 
export type Get_infoResult = [{ air_version: string; external_addresses: string[]; node_version: string; }, string]
export function get_info(
    config?: {ttl?: number}
): Promise<Get_infoResult>;

export function get_info(
    peer: FluencePeer,
    config?: {ttl?: number}
): Promise<Get_infoResult>;

 

export function gather_infos(
    peers: string[],
    config?: {ttl?: number}
): Promise<{ air_version: string; external_addresses: string[]; node_version: string; }[]>;

export function gather_infos(
    peer: FluencePeer,
    peers: string[],
    config?: {ttl?: number}
): Promise<{ air_version: string; external_addresses: string[]; node_version: string; }[]>;

 

export function gather_infos_par(
    peers: string[],
    config?: {ttl?: number}
): Promise<{ air_version: string; external_addresses: string[]; node_version: string; }[]>;

export function gather_infos_par(
    peer: FluencePeer,
    peers: string[],
    config?: {ttl?: number}
): Promise<{ air_version: string; external_addresses: string[]; node_version: string; }[]>;

