networks:
  fluence:
    # driver: bridge
    # ipam:
    #   config:
    #   - subnet: 10.50.10.0/24

services:
  fluence-1:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7771:7771
      - 9991:9991
    command:
      - -t=7771
      - -w=9991
      #- -x=127.0.0.1
      # - --bootstraps=/dns/fluence-1/tcp/7771
      - --local
      - --allow-private-ips
      - --aqua-pool-size=2
      - --external-maddrs
      - /dns4/fluence-1/tcp/7771
      - /dns4/fluence-1/tcp/9991/ws
      # 12D3KooWBM3SdXWqGaawQDGQ6JprtwswEg3FWGvGhmgmMez1vRbR
      - -k=hK62afickoeP2uZbmSkAYXxxqP8ozq16VRN7qfTP719EHC5V5tjrtW57BSjUr8GvsEXmJRbtejUWyPZ2rZMyQdq
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.10

  fluence-2:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7772:7772
      - 9992:9992
    command:
      - -t=7772
      - -w=9992
      #- -x=127.0.0.1
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
      - --allow-private-ips
      - --external-maddrs
      - /dns4/fluence-2/tcp/7772
      - /dns4/fluence-2/tcp/9992/ws
      # 12D3KooWQdpukY3p2DhDfUfDgphAqsGu5ZUrmQ4mcHSGrRag6gQK
      - -k=2WijTVdhVRzyZamWjqPx4V4iNMrajegNMwNa2PmvPSZV6RRpo5M2fsPWdQr22HVRubuJhhSw8BrWiGt6FPhFAuXy
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.20

  fluence-3:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7773:7773
      - 9993:9993
    command:
      - -t=7773
      - -w=9993
      #- -x=127.0.0.1
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
      - --allow-private-ips
      - --external-maddrs
      - /dns4/fluence-3/tcp/7773
      - /dns4/fluence-3/tcp/9993/ws
      # 12D3KooWRT8V5awYdEZm6aAV9HWweCEbhWd7df4wehqHZXAB7yMZ
      - -k=2n2wBVanBeu2GWtvKBdrYK9DJAocgG3PrTUXMharq6TTfxqTL4sLdXL9BF23n6rsnkAY5pR9vBtx2uWYDQAiZdrX
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.30

  fluence-4:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7774:7774
      - 9994:9994
    command:
      - -t=7774
      - -w=9994
      #- -x=127.0.0.1
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
      - --allow-private-ips
      - --external-maddrs
      - /dns4/fluence-4/tcp/7774
      - /dns4/fluence-4/tcp/9994/ws
      # 12D3KooWBzLSu9RL7wLP6oUowzCbkCj2AGBSXkHSJKuq4wwTfwof
      - -k=4zp8ucAikkjB8CmkufYiFBW4QCDUCbQG7yMjviX7W8bMyN5rfChQ2Pi5QCWThrCTbAm9uq5nbFbxtFcNZq3De4dX
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.40

  fluence-5:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7775:7775
      - 9995:9995
    command:
      - -t=7775
      - -w=9995
      #- -x=127.0.0.1
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
      - --allow-private-ips
      - --external-maddrs
      - /dns4/fluence-5/tcp/7775
      - /dns4/fluence-5/tcp/9995/ws
      # 12D3KooWBf6hFgrnXwHkBnwPGMysP3b1NJe5HGtAWPYfwmQ2MBiU
      - -k=3ry26rm5gkJXvdqRH4FoM3ezWq4xVVsBQF7wtKq4E4pbuaa6p1F84tNqifUS7DdfJL9hs2gcdW64Wc342vHZHMUp
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.40

  fluence-6:
    image: fluencelabs/fluence:minimal_add_addrs_to_conn_pool_103
    ports:
      - 7776:7776
      - 9996:9996
    command:
      - -t=7776
      - -w=9996
      #- -x=127.0.0.1
      - --aqua-pool-size=2
      - --bootstraps=/dns/fluence-1/tcp/7771
      - --allow-private-ips
      - --external-maddrs
      - /dns4/fluence-6/tcp/7776
      - /dns4/fluence-6/tcp/9996/ws
      # 12D3KooWPisGn7JhooWhggndz25WM7vQ2JmA121EV8jUDQ5xMovJ
      - -k=5Qh8bB1sF28uLPwr3HTvEksCeC6mAWQvebCfcgv9y6j4qKwSzNKm2tzLUg4nACUEo2KZpBw11gNCnwaAdM7o1pEn
    environment:
      RUST_LOG: trace,marine_core=info,particle_node=trace,trust_dns_resolver=info,builtins_deployer::builtins_deployer=trace,libp2p_noise=info,netlink_sys=info,netlink_proto=info,network=trace,aquamarine=info,aquamarine::actor=info,tokio_threadpool=info,tokio_reactor=info,mio=info,tokio_io=info,soketto=info,yamux=info,multistream_select=info,libp2p_secio=info,libp2p_websocket::framed=info,libp2p_ping=info,libp2p_core::upgrade::apply=info,libp2p_kad::kbucket=trace,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,cranelift_codegen=info,wasmer_wasi=info,async_io=info,polling=info,wasmer_interface_types_fl=info,particle_server::behaviour::identify=trace,libp2p_mplex=info,libp2p_identify=trace,walrus=info,particle_protocol::libp2p_protocol::upgrade=info,kademlia::behaviour=trace,async_std=info,trust_dns_proto=info
      WASM_LOG: info
    networks:
      fluence:
        # ipv4_address: 10.50.10.40
