/**
 *
 * This file is auto-generated. Do not edit manually: changes may be erased.
 * Generated by Aqua compiler: https://github.com/fluencelabs/aqua/.
 * If you find any bugs, please write an issue on GitHub: https://github.com/fluencelabs/aqua/issues
 * Aqua version: 0.7.4-336
 *
 */
import { Fluence, FluencePeer } from '@fluencelabs/fluence';
import {
    
    callFunction,
    registerService,
} from '@fluencelabs/fluence/dist/internal/compilerSupport/v3.js';


// Services
export interface GoodPeerDef {
    get_contact: (peer: string, callParams: CallParams<'peer'>) => { addresses: string[]; peer_id: string; } | null | Promise<{ addresses: string[]; peer_id: string; } | null>;
}
export function registerGoodPeer(service: GoodPeerDef): void;
export function registerGoodPeer(serviceId: string, service: GoodPeerDef): void;
export function registerGoodPeer(peer: FluencePeer, service: GoodPeerDef): void;
export function registerGoodPeer(peer: FluencePeer, serviceId: string, service: GoodPeerDef): void;
       

// Functions
 

export function get_contact(
    peer_: string,
    config?: {ttl?: number}
): Promise<{ addresses: string[]; peer_id: string; } | null>;

export function get_contact(
    peer: FluencePeer,
    peer_: string,
    config?: {ttl?: number}
): Promise<{ addresses: string[]; peer_id: string; } | null>;

